before_install:
  - sdk install java 17.0.12-tem  # Temurin JDK 17 (stable, widely used)
  - sdk use java 17.0.12-tem      # Switch to it for the build

install:
  - mvn install -DskipTests        # Runs your default build (optional, but ensures consistency)
