# Используем нужный JDK
jdk:
  - openjdk21

before_install:
  # JitPack автоматически подтягивает нужный JDK, но можно явно зафиксировать версию
  - echo "Using Java 21 for TreexClans build"

install:
  # Очищаем и собираем без тестов
  - mvn -B clean package -DskipTests
